# Generated by Django 3.1.7 on 2021-09-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='제목')),
                ('body', models.TextField(verbose_name='본문')),
                ('press', models.CharField(max_length=20, verbose_name='언론사')),
                ('journalist', models.CharField(max_length=20, verbose_name='기자')),
                ('comment_num', models.IntegerField(verbose_name='댓글 수')),
                ('angry', models.IntegerField(verbose_name='화나요')),
                ('warm', models.IntegerField(verbose_name='훈훈해요')),
                ('like', models.IntegerField(verbose_name='좋아요')),
                ('want', models.IntegerField(verbose_name='후속기사 원해요')),
                ('sad', models.IntegerField(verbose_name='슬퍼요')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
