# Generated by Django 3.1.7 on 2021-09-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='keyword',
            field=models.CharField(max_length=50, null=True, verbose_name='검색어'),
        ),
    ]
